---

- name: "1.4.1 | L1 | PATCH | Ensure AIDE is installed"
  block:
      - name: "1.4.1 | L1 | PATCH | Ensure AIDE is installed | Install AIDE"
        package:
            name: aide
            state: present

      - name: "1.4.1 | L1 | PATCH | Ensure AIDE is installed | Configure AIDE"
        command: /usr/sbin/aide --init -B 'database_out=file:/var/lib/aide/aide.db.gz'
        changed_when: false
        failed_when: false
        async: 45
        poll: 0
        args:
            creates: /var/lib/aide/aide.db.gz
        when: not ansible_check_mode
  when:
      - rhel8cis_config_aide
      - rhel8cis_rule_1_4_1
  tags:
      - level1-server
      - level1-workstation
      - scored
      - aide
      - patch
      - rule_1.4.1

- name: "1.4.2 | L1 | PATCH | Ensure filesystem integrity is regularly checked"
  ansible.builtin.copy:
    content: "/usr/sbin/aide --check"
    dest: /etc/cron.daily/aide
    mode: 0755
  when:
      - rhel8cis_rule_1_4_2
  tags:
      - level1-server
      - level1-workstation
      - scored
      - aide
      - file_integrity
      - patch
      - rule_1.4.2
